spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:file:~/employeedb;AUTO_SERVER=true
      driver-class-name: org.h2.Driver
      username: sa
      password: manage
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    baseline-on-migrate: true
  zipkin:
    base-url: http://localhost:9411/
    enabled: false
  
logging:
  file:
    name: /tmp/sblog/employee.log

    
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: false
    enabled: false
  
server:
  port: 8100
    
employee-service:
  defaultFirstName: DefaultFirst
  defaultLastName: DefaultLast
