spring:
  profiles:
    active: "dev"
  datasource:
    hikari:
      jdbc-url: jdbc:h2:file:~/employeedb;AUTO_SERVER=true
      driver-class-name: org.h2.Driver
      username: sa
      password: manage
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    baseline-on-migrate: true
  
logging:
  file:
    name: /tmp/sblog/employee.log

management:
  endpoints:
    web:
      exposure:
        include:
        - "*" 

server:
  port: 8100

---

spring:
  profiles: dev
   
employee-service:
  defaultFirstName: DefaultFirst-DEV
  defaultLastName: DefaultLast-DEV

---

spring:
  profiles: qa
   
employee-service:
  defaultFirstName: DefaultFirst-QAA
  defaultLastName: DefaultLast-QAA

---

spring:
  profiles: prod
   
employee-service:
  defaultFirstName: DefaultFirst
  defaultLastName: DefaultLast
