spring:
  profiles:
    active: "dev"

management:
  endpoints:
    web:
      exposure:
        include:
        - "*" 

---

spring:
  profiles: dev
   
house-service:
  houseNumber: Wakad
  houseStreet: Pune

---

spring:
  profiles: qa
   
house-service:
  houseNumber: DefaultFirst-Quality
  houseStreet: Delhi

---

spring:
  profiles: prod
   
house-service:
  houseNumber: DefaultFirst
  houseStreet: Gurgaon
