spring:
  profiles:
    active: "dev"

management:
  endpoints:
    web:
      exposure:
        include:
        - "*" 

---

spring:
  profiles: dev
   
house-service:
  houseNumber: DefaultFirst-DEV

---

spring:
  profiles: qa
   
house-service:
  houseNumber: DefaultFirst-Quality

---

spring:
  profiles: prod
   
house-service:
  houseNumber: DefaultFirst
